apps/characters/urls.py
from django.urls import path

from characters.views import (
    CharactersListView,
    CharactersDetailView,
    download_characters,
)

app_name = "characters"

urlpatterns = [
    path("", CharactersListView.as_view(), name="characters-list"),
    path("download/", download_characters, name="download-characters"),
    path("<int:pk>/", CharactersDetailView.as_view(), name="characters-detail"),
]

sw_explorer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('characters/', include('characters.urls')),
    path('', TemplateView.as_view(template_name="base_generic.html"))
]

apps/characters/models.py
from django.db import models

from core.models import BaseModel

class CharactersCsvFile(BaseModel):
    file = models.FileField(upload_to="characters")
    class Meta:
        ordering = ['-ctime']

apps/core/models.py
from django.db import models

class BaseModel(models.Model):


    ctime = models.DateTimeField(auto_now_add=True)
    mtime = models.DateTimeField(auto_now=True)
    class Meta:
        abstract= True

apps/characters/views.py
from django.views.generic import ListView, DetailView
from django.conf import settings
from django.contrib import messages
from django.http import Http404, HttpResponseRedirect, HttpRequest
from django.shortcuts import redirect
import petl as etl

from characters.models import CharactersCsvFile
from characters.importer import CharacterImporter

DEFAULT_ROWS_LIMIT = 10


class CharactersListView(ListView):
    paginate_by = 10
    model = CharactersCsvFile


class CharactersDetailView(DetailView):
    model = CharactersCsvFile

    def get_records(self, count_columns: str, limit: int, model: CharactersCsvFile) -> dict:
        dataset = etl.fromcsv(settings.MEDIA_ROOT / model.file.name)
        headers = etl.header(dataset)
        if count_columns:
            columns = count_columns.split(",")[:-1]
            aggregated_dataset = etl.aggregate(
                dataset[: limit + 1], key=columns, aggregation=len
            )
            aggregated_headers = etl.header(aggregated_dataset)
            aggregated_records = etl.records(aggregated_dataset)
        else:
            aggregated_headers = aggregated_records = None
        records = etl.records(dataset)[:limit]
        return {
            "headers": headers,
            "records": records,
            "limit": limit,
            "count_columns": count_columns,
            "aggregated_headers": aggregated_headers,
            "aggregated_records": aggregated_records,
        }

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        parameters = self.request.GET
        limit = int(parameters.get("limit", DEFAULT_ROWS_LIMIT))
        count_columns = parameters.get("count_columns", "")
        try:
            context_records = self.get_records(count_columns, limit, context["object"])
        except FileNotFoundError:
            raise Http404()
        return context | context_records


def download_characters(request: HttpRequest) -> HttpResponseRedirect:
    importer = CharacterImporter()
    if imported_file := importer.import_data():
        messages.success(request, f"Added new file with id {imported_file.id} .")
    else:
        messages.error(request, "Unable to fetch new data at this point")
    return redirect("characters:characters-list")

apps/core/views.py
from django.shortcuts import render

# Create your views here.

apps/characters/templates/characters/characterscsvfile_detail.html
{% extends "base_generic.html" %}
{% load custom_text_filters %}
{% block content %}
<h1>Imported: {{ characterscsvfile.ctime|date:'Y-m-d H:i' }}</h1>
<button type="button" onclick="location.href='{% url 'characters:characters-detail' characterscsvfile.id %}?limit={{ limit|add:"10" }}&count_columns={{count_columns}}'" class="btn btn-primary">Load more</button>
{% if aggregated_headers %}
<table class="table">
  <thead>
     <tr>
        <th scope="col">#</th>
        {% for header in aggregated_headers %}
        <th scope="col">{{header}}</th>
        {% endfor %}

     </tr>
  </thead>
  <tbody>
     {% for row in aggregated_records %}
     <tr>
        <th scope="row">{{ forloop.counter }}</th>
        {% for column in row %}
        <td>{{column}}</td>
        {% endfor %}
     </tr>
     {% endfor %}
  </tbody>
</table>
{% endif %}
<h2>Click on column names to count combination of values</h2>
<table class="table">
   <thead>
      <tr>
         <th scope="col">#</th>
         {% for header in headers %}
         <th scope="col"><button type="button" onclick=
          "location.href='{% url 'characters:characters-detail' characterscsvfile.id %}?limit={{limit}}&count_columns={% if not header in count_columns %}{{ header }},{{count_columns}}{% else %}{{ count_columns|cut_from_count_columns:header }}{% endif %}'"
           class="btn {% if header in count_columns %}btn-success{% else %}btn-light{% endif %}">{{header}}</button></th>
         {% endfor %}
      </tr>
   </thead>
   <tbody>
      {% for row in records %}
      <tr>
         <th scope="row">{{ forloop.counter }}</th>
         {% for column in row %}
         <td>{{column}}</td>
         {% endfor %}
      </tr>
      {% endfor %}
   </tbody>
</table>

{% endblock %}

apps/characters/templates/characters/characterscsvfile_list.html
{% extends "base_generic.html" %}
{% block content %}

<button type="button" onclick="location.href='{% url 'characters:download-characters' %}'" class="btn btn-primary">Download new</button>
<div>
    <ul class="list-group">
{% for file in page_obj %}
<li class="list-group-item"><a href="{% url 'characters:characters-detail' file.id %}">{{file.id}} - {{ file.ctime|date:'Y-m-d H:i' }}</a></li>
{% endfor %}
</ul>
</div>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

sw_explorer/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Sw explorer</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'characters:characters-list' %}">Characters</a></li>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
</body>
</html>